int _putchar(char c);
void *malloc_checked(unsigned int b);
char *string_nconcat(char *s1, char *s2, unsigned int n);
void *_calloc(unsigned int nmemb, unsigned int size);
int *array_range(int min, int max);
void *_realloc(void *ptr, unsigned int old_size, unsigned int new_size);
void print_error(void);
void digit_check(char *s);
unsigned long long int _mul(unsigned long long int a, unsigned long long int b);
unsigned int _strtoi(char *s);
void print_number(unsigned long long int n);
